# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
